name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout my repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Build the Docker images without using cache
      - name: Build Docker images
        run: docker-compose build --no-cache

      # Run tests inside the container
      - name: Run pytest inside container
        run: docker-compose run --rm web sh -c "pytest app/test_app.py"

      # (Optional) Shut down containers and clean up
      - name: Shut down Docker Compose
        run: docker-compose down

